{{- if .Values.imageBuild.enabled }}
{{- /* The builder's metrics Service. */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-oci-composer.builderFullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-oci-composer.componentLabels" (dict "ctx" . "component" "builder") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ include "kube-oci-composer.port" .Values.imageBuild.metricsBindAddress }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kube-oci-composer.componentSelectorLabels" (dict "ctx" . "component" "builder") | nindent 4 }}
{{- end }}
