{{- if .Values.imageComposition.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-oci-composer.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-oci-composer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ include "kube-oci-composer.port" .Values.operator.metricsBindAddress }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kube-oci-composer.componentSelectorLabels" (dict "ctx" . "component" "composer") | nindent 4 }}
{{- end }}
